siteUid: null
sortOrder: 17
template: /contact/extras/suppress-edit-submissions
uriParts:
  - contact/extras/suppress-edit-submissions/edit/
  -
    - token
    - \w+
uriPattern: 'contact/extras/suppress-edit-submissions/edit/<token:\w+>'
