field: 3fd7e253-fbd2-41da-8cea-0a658d896ef5 # Team Members
fieldLayouts:
  60a4959f-08fc-4334-9e12-8fedcf16bbb8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b1c724d4-e5bb-4114-8ee2-47f0bc624d36 # Team Member Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7e33d08-35cd-45eb-aa8e-7184c3298ffe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f425df24-0e8f-401d-bebd-001154524f4f # Team Member Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ba69e4d-1132-4904-a488-4160dd9c485a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d41cd667-380d-4e3d-b2cb-0a26088bcb0b # Team Member Role
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a946a77-fe71-44d6-96b6-67c53e978795
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 907b0ce0-5929-4006-8360-3c0ef5068b32
        userCondition: null
fields:
  b1c724d4-e5bb-4114-8ee2-47f0bc624d36: # Team Member Image
    columnSuffix: wrfkcwht
    contentColumnType: string
    fieldGroup: null
    handle: teamMemberImage
    instructions: null
    name: 'Team Member Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:6dd39846-bea4-42c9-bd98-a569eba1b583' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:6dd39846-bea4-42c9-bd98-a569eba1b583' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  d41cd667-380d-4e3d-b2cb-0a26088bcb0b: # Team Member Role
    columnSuffix: yrhhavaa
    contentColumnType: text
    fieldGroup: null
    handle: teamMemberRole
    instructions: null
    name: 'Team Member Role'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f425df24-0e8f-401d-bebd-001154524f4f: # Team Member Name
    columnSuffix: jennuzfj
    contentColumnType: text
    fieldGroup: null
    handle: teamMemberName
    instructions: null
    name: 'Team Member Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: teamMember
name: TeamMember
sortOrder: 1
