fieldLayouts:
  2a269be7-5c41-43cd-86db-b204373be7f9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 17efeb9f-f7d5-40c3-bbe8-d0ab325f55dd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6a1d3069-5b65-431d-8f9e-9e14f1acc886
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
