columnSuffix: null
contentColumnType: string
fieldGroup: 6d985331-a787-42ff-9fae-5b290291dda2 # Common
handle: serviceCard
instructions: null
name: 'Service Card'
searchable: false
settings:
  contentTable: '{{%matrixcontent_servicecard}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
