defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  a64a7406-0863-4e3b-a98e-d33ef46b8d72: # Mr.Rover
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
